application/__init__.py
from logging import (
    getLogger,
    Logger
)
from application.data import init_app
from flask import Flask
import os.path as path
import application.log_configuration as log
import application.blueprints as bl
import tomllib

logger: Logger = getLogger(__name__)


def make_app():
    app: Flask = Flask(__name__, instance_relative_config=True)
    assert path.exists(app.instance_path), "Отсутствует папка instance с конфигурацией."

    app.config.from_mapping({
        "DATABASE_NAME": "main.db",
        "KEY": "c496993eeb9bb9a42bf39fdac739acd9",
        "CITIES": "cities.example.txt"
    })

    app.config["DATABASE_PATH"] = path.join(app.instance_path, app.config["DATABASE_NAME"])
    
    with app.app_context():
        init_app()

    log.configure_log(path.join(app.instance_path, "app.log"))

    app.register_blueprint(bl.pages)
    app.register_blueprint(bl.facts)
    return app

    

application/blueprints/__init__.py
from application.blueprints.pages import pages
from application.blueprints.facts import facts

application/blueprints/facts.py
from flask import (
    render_template,
    request,
    Blueprint
)
from typing import Optional
from random import randint
import application.web_api as web_api

"""Для рендера страницы с случайными погодными фактами."""

facts: Blueprint = Blueprint('facts', __name__, url_prefix="/facts")
@facts.route('/')
def random_facts():
    count: Optional[str] = request.mimetype_params.get("count", 6)
    facts: set[str] = web_api.weather_facts(count)
    return render_template(f'random_fact.html', random_facts=facts)

application/blueprints/pages.py
from flask import (
    render_template,
    abort,
    Blueprint
)
from jinja2 import TemplateNotFound

"""Для рендера статических (т.е. работающих на одном лишь .html и JS) страниц. (см. https://flask.palletsprojects.com/en/2.3.x/blueprints/)"""

pages: Blueprint = Blueprint('pages', __name__)
@pages.route('/', defaults={'page': 'index'})
@pages.route('/<page>')
def show(page):
    try:
        return render_template(f'pages/{page}.html')
    except TemplateNotFound:
        abort(404)

application/util/__init__.py
from application.util.iter import *

application/web_api/__init__.py
from logging import (
    getLogger,
    Logger
)
from concurrent.futures import ProcessPoolExecutor
from functools import partial
from typing import Iterator
from time import perf_counter
from random import sample
from flask import current_app
from application.web_api.data import Weather
from application.web_api.weather import weather
from application.web_api.lang import inflect
import application.util as util
import os.path as path

logger: Logger = getLogger(__name__)



CITIES: list[str] = []


def init_cities() -> None:
    logger.info("Заполняем список городов.")
    with open(path.join(current_app.instance_path, current_app.config["CITIES"]), "r", encoding="utf-8") as fp:
        for line in fp:
            line = line.strip()
            if not line:
                continue
            CITIES.append(line)
    if not len(CITIES):
        logger.critical("Файл с городами пуст!")


def get_cities(count: int) -> list[str]:
    if not len(CITIES):
        init_cities()
    return sample(CITIES, k=count)


def weather_facts(count: int) -> set[str]:
    start: float = perf_counter()
    strings: set[str] = set()
    cities: list[str] = get_cities(count*2)
    local_weather: tuple[Weather] = (weather(city) for city in cities)
    for pair in util.chunks(local_weather, 2):
        weather1, weather2 = (info.description for info in pair)
        city1, city2 = (inflect(info.name, "loct").title()
                        for info in pair)
        strings.add(f"В {city1} - {weather1}, а в {city2} - {weather2}.")
    logger.debug(f"Длительность выполнения: {perf_counter() - start}")
    return strings

application/templates/pages/addiction_info.html
<!DOCTYPE html>
<html>
<head>
    <title>Технологические зависимости</title>
    <link rel="stylesheet" href="..\static\css\style.css">
</head>
<body>
    <article class="parent_embed" id="adc_list">
        <strong>Вот самые распространённые технологические зависимости:</strong>
        <ul>
            <li><strong>Социальные сети и мессенджеры:</strong> социальные сети уменьшают время, которое мы проводим в реальном мире. А еще привыкаем к постоянному обновлению новостей и сообщений.</li>
            <li><strong>Смартфоны и планшеты:</strong> смартфоны и планшеты могут стать привычным способом общения с миром, и люди могут стать зависимыми от постоянной проверки уведомлений! </li>
            <li><strong>Игры и онлайн-развлечения:</strong> игры и онлайн-развлечения могут стать зависимостью, особенно в случаях, когда люди проводят слишком много времени в виртуальном мире вместо реальной жизни.</li>
            <li><strong>Интернет-шопинг и онлайн-покупки:</strong> люди могут стать зависимыми от онлайн-шопинга, особенно если они используют его для удовлетворения эмоциональных потребностей.</li>
            <li><strong>Онлайн-видео и потоковые сервисы:</strong> слишком много времени на YouTube и Twitch - тоже зависимость, которая может привести к потере времени и уменьшению интереса к реальному миру.</li>
            <li><strong>Умные устройства для дома:</strong> люди могут стать зависимыми от использования умных устройств для дома (например, голосовые помощники), что может привести к уменьшению навыков коммуникации и потере способности принимать решения.</li>
            <li><strong>Технологии виртуальной и дополненной реальности:</strong> виртуальные очки могут привести к уменьшению интереса к реальному миру и потере навыков коммуникации, если проводить в виртуальном мире больше времени, чем в реальном.</li>
        </ul>
    </article>
    <article class="parent_embed">
        <article class="embed" id="rb_methods">
            <strong>Как можно бороться с этими зависимостями?</strong>
            <ul>
                <li>Установить <strong>лимиты на время</strong>, проведенное в Интернете и на использование устройств.</li>
                <li><strong>Разнообразить свои интересы и занятия</strong>, чтобы не ограничиваться только использованием технологий.</li>
                <li>Искать <strong>новые способы общения</strong> с окружающим миром, в том числе с людьми, чтобы уменьшить зависимость от социальных сетей и мессенджеров.</li>
                <li><strong>Регулярные перерывы и отключение смартфона</strong>, чтобы не утомлять глаза и разум.</li>
                <li><strong>Планирование</strong> времени без использования технологий, чтобы расслабиться и отдохнуть.</li>
                <li>Старайтесь <strong>быть более осознанными</strong> в отношении использования технологий, и задавайте себе вопросы, когда чувствуете, что становитесь слишком зависимыми.</li>
            </ul>
        </article>
    </article>
</body>
</html>

application/templates/pages/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Главная страница</title>
    <link rel="stylesheet" href="..\static\css\style.css">
</head>
<body>
    <article class="parent_embed" id="adc_list">
        <strong>Добро пожаловать на сайт!</strong>
        <p>У нас имеется много всего. Осматривайтесь, не стесняйтесь!</p>
    </article>
    <article class="parent_embed">
        <article class="embed" id="site-links">
            <strong>Список ссылок сайта:</strong>
            <ul style="list-style-type: '» ';">
                <li>Возможно, вы хотите узнать <a href="{{ url_for('.show', page='addiction_info') }}">какие технологические зависимости существуют?</a></li>
                <li>Возможно, вы хотите узнать <a href="{{ url_for('facts.random_facts')}}">какой-то новый случайный факт?</a></li>
            </ul>
        </article>
    </article>
</body>
</html>

application/templates/random_fact.html
<!DOCTYPE html>
<html>
<head>
    <title>Случайный факт</title>
    <link rel="stylesheet" href="..\static\css\style.css">
</head>
<body>
    <article class="parent_embed">
        <article class="embed" id="facts">
            <strong>Интересные факты:</strong>
            <ul>
                {% for fact in random_facts %}
                <li><p>{{ fact }}</p></li>
                {% endfor %}
            </ul>
        </article>
    </article>
</body>
</html>